### Instructions

Make a duplicate copy of google colab by clicking **File/ Save a copy in Drive option.** A duplicate copy will get created. It will open up in the new tab on your web browser .After that change **share settings**

#### CO-1 Review of Python Programming

This colab is designed for you to practice and solve the activities that are based on the following concepts:

 1. NumPy Arrays
 2. Matrix operations (using vectorization) and Trasformation
 3. Python Lists
 4. SVD using Python.


---

Import Library

In [ ]:
# import libraries
import numpy as np

Create 1D Array contain 9 elements print its shape

In [ ]:
# write code here
list=[1,2,3,4,5,6,7,8,9]
print(type(list))
arr=np.array(list)
print(arr)
print(type(arr))



<class 'list'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


Reshape the array  to a 3x3 matrix

In [ ]:
# Write your code here
x=np.array([1,2,3,4,5,6,7,8,9])
print(x)
x.shape=[3,3]
print(x)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Add two 3x2 matrices and print the sum

In [ ]:
# Write your code here
a=np.array([1,3,2,5,4,6])
b=np.array([1,2,3,4,5,6])
a.shape=[2,3]
b.shape=[2,3]
print(a)
print(a.shape)
print(b)
c=a+b
print("Sum of Matrix\n",c)

[[1 3 2]
 [5 4 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
Sum of Matrix
 [[ 2  5  5]
 [ 9  9 12]]


Multiply Two matrices of order 3x3 and 3x4

In [ ]:
# Write your code here
a=np.array([[1,2,3],[3,4,5],[3,5,7]])
b=np.array([[1,2,3,4],[4,3,2,1],[5,6,4,3]])
print(a.shape)
print(b.shape)
print(a)
print(b)
d=np.dot(a,b)
print("Multiplication of Matrix\n",d)

(3, 3)
(3, 4)
[[1 2 3]
 [3 4 5]
 [3 5 7]]
[[1 2 3 4]
 [4 3 2 1]
 [5 6 4 3]]
Multiplication of Matrix
 [[24 26 19 15]
 [44 48 37 31]
 [58 63 47 38]]


perform Elementwise multiplication of two 2x2 matrices

In [ ]:
# Write your code here
a=np.array([[1,3],[3,4]])
b=np.array([[2,5],[2,6]])
r=a*b
print("Prodct\n",r)

Prodct
 [[ 2 15]
 [ 6 24]]


Transpose and Invers of a 3x3 matrix

In [ ]:
# Write your code here
a=np.array([[1,3],[3,4]])
print(a)
t=a.T
print("Transpose\n",t)
inva=np.linalg.inv(a)
print("Inverse\n",inva)


[[1 3]
 [3 4]]
Transpose
 [[1 3]
 [3 4]]
Inverse
 [[-0.8  0.6]
 [ 0.6 -0.2]]


Mathematical Operations on a 3x3 matrix
increment all the elements of a matrix by 5
multiply all the the elements of a matrix by 5
calculate the mean and SD of elements of a matrix


In [ ]:
# Write your code here
a=np.array([[1,3],[3,4]])
print(a)
incr_array_a=a*5
print("Incremented Matrix\n",incr_array_a)
mean_value=np.mean(a)
print("Mean\n",mean_value)
std_dev=np.std(a)
print("Standard Deviation\n",std_dev)




[[1 3]
 [3 4]]
Incremented Matrix
 [[ 5 15]
 [15 20]]
Mean
 2.75
Standard Deviation
 1.0897247358851685


Perform SVD on a 3x2 matrix
(use np.linalg.svd) print the values of U, S V

In [ ]:
# Write your code here
a=np.array([[1,3],[3,4],[5,6]])
print(a)
U,S,V=np.linalg.svd(a)
print("U matrix\n",U)
print("S matrix\n",S)
print("V matrix\n",V)


[[1 3]
 [3 4]
 [5 6]]
U matrix
 [[-0.30792099  0.93210569  0.19069252]
 [-0.51342088  0.00594707 -0.85811633]
 [-0.80098918 -0.36213755  0.47673129]]
S matrix
 [9.73859095 1.0769616 ]
V matrix
 [[-0.60102427 -0.79923077]
 [-0.79923077  0.60102427]]


Indexing and Slicing
Create 3x4 array

1.  Print last  row elements
2.  Print last column elements
3.  Print all elements in the array except first row first column











In [ ]:
# write code here
a=np.array([[1,2,3,6],[2,4,5,1],[5,1,2,2]])
print(a)
print(a.shape)
element=a[2]
print("Last row elements\n",element)
b=a[:,-1]
print("Last column Elements\n",b)
c=a[1: ,1:]
print("All elements except first row,first column\n",c)


[[1 2 3 6]
 [2 4 5 1]
 [5 1 2 2]]
(3, 4)
Last row elements
 [5 1 2 2]
Last column Elements
 [6 1 2]
All elements except first row,first column
 [[4 5 1]
 [1 2 2]]


Convert the array to a list

In [ ]:
#write your code here
my_array=np.array([1,2,3,4,5])
my_list=my_array.tolist()
print(my_list)

[1, 2, 3, 4, 5]


####  Create a 3 X 3 Matrix with values ranging from 2 to 10.

**For Example**:

```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
```

  - **Step 1**: Import `numpy` module.

  - **Step 2**: Use `arange()` function to create array of numbers from 2 to 10
  - **Step 3**: Use `reshape()` function to reshape your array  having 3 rows and 3 columns. Store this reshaped array in a variable `x`.
.



In [ ]:
# Write your code here
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)



[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


---

#### Create and Update a Null NumPy Array

Create a null NumPy array of size 9 and update the sixth value to 11.

A null array is basically an array with all elements as `0`.

- **Step 1:** Import the Numpy module as `np`.

- **Step 2**: Create a null array by passing the size i.e. `10` inside the `np.zeros()` function and store it in a variable `null_arr`.

- **Step 3**: Print the null array.

- **Step 4**: Now update the 6th element of the array by using **list indexing** method.

- **Step 5**: Print the updated array in the output.



In [ ]:
# Write your code here
import numpy as np
null_arr=np.zeros(10)
print(null_arr)
null_arr[2]=3
print(null_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 3. 0. 0. 0. 0. 0. 0. 0.]


In the above program we have created a null array by using the `np.zeros()` function of the `numpy` module.



---

#### Populate a Number List

Write a program that populates a list by numbers that lies in the range of 0 - 50 and also divisible by 5. Use List Comprehension method.





In [ ]:
# Write a program to populate a number list divisible by 5 in a range 0 - 50
list1=[num for num in range(51) if num%5 == 0]
print(list1)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
